version: '2'

services:
  mariadb:
       image: mariadb:latest
       environment:
         - MYSQL_ROOT_PASSWORD=VMware1!
         - MYSQL_DATABASE=phpipam
         - MYSQL_USER=phpipam
         - MYSQL_PASSWORD=VMware1!
       restart: always
       logging:
        driver: json-file
        options:
          max-size: "100m"
          max-file: "3"
          labels: "mariadb"

  phpipam:
       image: burkeazbill/docker-phpipam
       environment:
          - MYSQL_DB_HOSTNAME=mariadb
          - MYSQL_DB_USERNAME=phpipam
          - MYSQL_DB_PASSWORD=VMware1!
          - MYSQL_DB_NAME=phpipam
          - MYSQL_DB_PORT=3306
       ports:
          - "8181:80"
       restart: always
       depends_on:
          - mariadb
       logging:
         driver: json-file
         options:
           max-size: "100m"
           max-file: "3"
           labels: "phpipam"
  myadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_HOST=mariadb
        - PMA_PORT=3306
        - PMA_USER=phpipam
        - PMA_PASSWORD=VMware1!
      ports:
        - "8282:80"
      restart: always
      depends_on:
        - mariadb